### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by allaire** [mperham/inspeqtor#148]
I'm getting the following error on Ubuntu 16.04 using upstart. Everything was working correctly until recently after (I think) an apt upgrade. Any hints? When I comment my .inq file below I can start it successfully.

```
check service agendrix-web@5000.service
  if memory:total_rss > 2g for 4 cycles then alert, reload
```

```
I 2018-05-30T21:13:12.064625Z 13142 Detected upstart in /etc/init
I 2018-05-30T21:13:12.064709Z 13142 Detected systemd in /etc/systemd
I 2018-05-30T21:13:12.064956Z 13142 Detected init.d in /etc/init.d/
I 2018-05-30T21:13:12.065603Z 13142 Expose now available at port 4677
I 2018-05-30T21:13:12.069121Z 13142 Found systemd/agendrix-web@5000.service with status Up/12859
panic: runtime error: index out of range

goroutine 15 [running]:
panic(0x764f60, 0xc42000a0d0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/mperham/inspeqtor/metrics.(*processStorage).captureVM(0xc420012b90, 0x323b, 0xc4200b7701, 0x0)
	/Users/mike/src/github.com/mperham/inspeqtor/metrics/process.go:361 +0x2fc
github.com/mperham/inspeqtor/metrics.(*processStorage).Collect(0xc420012b90, 0x323b, 0x7c4a34, 0x2)
	/Users/mike/src/github.com/mperham/inspeqtor/metrics/process.go:226 +0x8b
github.com/mperham/inspeqtor.(*Service).Collect(0xc4200da570, 0x0, 0xc4200cecf0)
	/Users/mike/src/github.com/mperham/inspeqtor/types.go:148 +0x21d
created by github.com/mperham/inspeqtor.(*Inspeqtor).scan
	/Users/mike/src/github.com/mperham/inspeqtor/inspeqtor.go:295 +0x217
```

**Comment by allaire** [comment]
@gmartsenkov are you having the same issue?

**Comment by mperham** [comment]
The code is reading `/proc/<pid>/status` and looking for the `VmRSS` line.  That error would occur if there was an empty line in the output. Can you show me what `/proc/1357/status` looks like?

**Comment by allaire** [comment]
@mperham Hi Make, here you go:

```
Name:	ruby
State:	S (sleeping)
Tgid:	1357
Ngid:	0
Pid:	1357
PPid:	1
TracerPid:	0
Uid:	1001	1001	1001	1001
Gid:	1002	1002	1002	1002
FDSize:	256
Groups:	1001 1002
NStgid:	1357
NSpid:	1357
NSpgid:	1357
NSsid:	1357
VmPeak:	  200632 kB
VmSize:	  140688 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   17856 kB
VmRSS:	   17856 kB
VmData:	   78352 kB
VmStk:	    8188 kB
VmExe:	    3188 kB
VmLib:	    6704 kB
VmPTE:	     156 kB
VmPMD:	      12 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
Threads:	3
SigQ:	0/7930
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	00000001c2317e4f
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
Seccomp:	0

Speculation_Store_Bypass:	vulnerable
Cpus_allowed:	7fff
Cpus_allowed_list:	0-14
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	13074
nonvoluntary_ctxt_switches:	415
```

**Comment by mperham** [comment]
Yep, there's the blank line.

**Comment by allaire** [comment]
Oh I see you made a fix, awesome! My ansible role is using apt to install. Are you going to cut a release as well?

Thanks so much!

**Comment by mperham** [comment]
I'm working on #146 and will release 2.0 with the Pro functionality sometime soon.

**Comment by allaire** [comment]
Great, and in the meantime, is there a way to patch the issue on my side?

**Comment by allaire** [comment]
@mperham So I compiled by hand and now I'm getting this:

```
May 31 21:07:22 app-01 inspeqtor[16443]: panic: runtime error: index out of range
May 31 21:07:22 app-01 inspeqtor[16443]: goroutine 15 [running]:
May 31 21:07:22 app-01 inspeqtor[16443]: github.com/mperham/inspeqtor/metrics.totalRssCollector(0x54d, 0xc42001c7d0, 0x0, 0x0)
May 31 21:07:22 app-01 inspeqtor[16443]:         /Users/allaire/.go/src/github.com/mperham/inspeqtor/metrics/process.go:158 +0x785
May 31 21:07:22 app-01 inspeqtor[16443]: github.com/mperham/inspeqtor/metrics.(*processStorage).Collect(0xc42001c7d0, 0x54d, 0x848dc0, 0xc420065ef0)
May 31 21:07:22 app-01 inspeqtor[16443]:         /Users/allaire/.go/src/github.com/mperham/inspeqtor/metrics/process.go:238 +0x12f
May 31 21:07:22 app-01 inspeqtor[16443]: github.com/mperham/inspeqtor.(*Service).Collect(0xc420065ef0, 0x847900, 0xc4200532a0)
May 31 21:07:22 app-01 inspeqtor[16443]:         /Users/allaire/.go/src/github.com/mperham/inspeqtor/types.go:148 +0x1a1
May 31 21:07:22 app-01 inspeqtor[16443]: created by github.com/mperham/inspeqtor.(*Inspeqtor).scan
May 31 21:07:22 app-01 inspeqtor[16443]:         /Users/allaire/.go/src/github.com/mperham/inspeqtor/inspeqtor.go:293 +0x186
May 31 21:07:22 app-01 systemd[1]: inspeqtor.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 31 21:07:22 app-01 systemd[1]: inspeqtor.service: Unit entered failed state.
May 31 21:07:22 app-01 systemd[1]: inspeqtor.service: Failed with result 'exit-code'.
May 31 21:07:23 app-01 systemd[1]: inspeqtor.service: Service hold-off time over, scheduling restart.
May 31 21:07:23 app-01 systemd[1]: Stopped Inspeqtor.
May 31 21:07:23 app-01 systemd[1]: inspeqtor.service: Start request repeated too quickly.
```

**Comment by allaire** [comment]
So I'm no Go expert (never used it before), but I took your fix:

```go
if len(line) == 0 {
  continue
}
```

and I copied where I found `for _, line := range lines {` in process.go:

```go
package metrics

import (
	"errors"
	"fmt"
	"io/ioutil"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/mperham/inspeqtor/util"
)

var (
	timeRegexp = regexp.MustCompile("\\A(\\d+):(\\d\\d).(\\d\\d)\\z")
)

type dynamicCollector func(int, *processStorage) error

type processStorage struct {
	*storage
	path string
	// TODO refactor this to be a Source
	dyncol         []dynamicCollector
	daemonSpecific []Source
}

func NewProcessStore(path string, cycleSeconds uint) Store {
	store := &processStorage{
		storage: &storage{map[string]*family{}},
		path:    path,
	}

	tickPercentage := func(cur, prev float64) float64 {
		return float64(((cur - prev) / float64(cycleSeconds*ClkTck)) * 100)
	}

	store.DeclareGauge("memory", "rss", DisplayInMB)
	store.DeclareCounter("cpu", "user", tickPercentage, DisplayPercent)
	store.DeclareCounter("cpu", "system", tickPercentage, DisplayPercent)
	store.DeclareCounter("cpu", "total_user", tickPercentage, DisplayPercent)
	store.DeclareCounter("cpu", "total_system", tickPercentage, DisplayPercent)
	return store
}

func (ps *processStorage) Prepare() error {
	for _, x := range ps.daemonSpecific {
		err := x.Prepare()
		if err != nil {
			return err
		}
	}
	return nil
}

func (ps *processStorage) AddSource(name string, config map[string]string) (Source, error) {
	for _, x := range ps.daemonSpecific {
		if x.Name() == name {
			return x, nil
		}
	}
	builder := Sources[name]
	if builder == nil {
		return nil, nil
	}
	util.Info("Activating metrics for %s", name)
	src, err := builder(config)
	if err != nil {
		return nil, err
	}

	m, ok := src.(MandatorySource)
	if ok && m.Mandatory() {
		util.Debug("Registering all metrics for %s", name)
		descs := src.ValidMetrics()
		for _, d := range descs {
			if d.MetricType == Counter {
				ps.DeclareCounter(name, d.Name, nil, d.Display)
			} else {
				ps.DeclareGauge(name, d.Name, d.Display)
			}
		}
	}

	ps.daemonSpecific = append(ps.daemonSpecific, src)
	return src, nil
}

func (ps *processStorage) Watch(family, name string) error {
	if family == "memory" && name == "total_rss" {
		ps.DeclareGauge("memory", "total_rss", DisplayInMB)
		ps.dyncol = append(ps.dyncol, totalRssCollector)
		return nil
	}

	for _, x := range ps.daemonSpecific {
		if x.Name() == family {
			descs := x.ValidMetrics()
			for _, d := range descs {
				if d.Name == name {
					if d.MetricType == Counter {
						ps.DeclareCounter(family, name, nil, d.Display)
					} else {
						ps.DeclareGauge(family, name, d.Display)
					}
					x.Watch(name)
					return nil
				}
			}
			return fmt.Errorf("No such metric: %s:%s", family, name)
		}
	}

	return nil
}

func (ps *processStorage) Load(values ...interface{}) {
	if len(values) > 0 {
		ps.fill(values...)
	}
}

type processEntry struct {
	pid  int
	ppid int
	rss  int64
}

/*
  Collecting total RSS for a process is actually rather involved on Linux.
	Because of this, we only collect the value if the user defines a rule
	for it.  This is a "dynamicCollector".
*/
func totalRssCollector(mypid int, ps *processStorage) error {
	matches, err := filepath.Glob(fmt.Sprintf("%s/[1-9][0-9]*/status", ps.path))
	if err != nil {
		return err
	}
	var live []processEntry

	for _, file := range matches {
		pe := processEntry{}

		data, err := ioutil.ReadFile(file)
		if err != nil {
			// race condition between globbing and reading, process
			// can disappear at any moment
			continue
		}

		lines, err := util.ReadLines(data)
		if err != nil {
			return err
		}
		for _, line := range lines {
			if len(line) == 0 {
				continue
			}
			if line[0] == 'V' || line[0] == 'P' {
				items := strings.Split(line, ":")
				switch items[0] {
				case "Pid":
					pid, err := strconv.Atoi(strings.TrimSpace(items[1]))
					if err != nil {
						return err
					}
					pe.pid = pid
				case "PPid":
					ppid, err := strconv.Atoi(strings.TrimSpace(items[1]))
					if err != nil {
						return err
					}
					pe.ppid = ppid
				case "VmRSS":
					vals := strings.Fields(items[1])
					val, err := strconv.ParseInt(vals[0], 10, 64)
					if err != nil {
						return err
					}
					pe.rss = val * 1024
				}
			}
		}

		if pe.rss != 0 {
			live = append(live, pe)
		}
	}
	util.DebugDebug("Calculating %d processes", len(live))

	rss := memoryFor(live, mypid)
	util.DebugDebug("Total RSS for %d: %d", mypid, rss)

	ps.Save("memory", "total_rss", float64(rss))
	return nil
}

// recursively walk the array, looking for children, grandchildren, etc
func memoryFor(procs []processEntry, curpid int) int64 {
	var rss int64
	for _, entry := range procs {
		if entry.pid == curpid {
			rss += entry.rss
		} else if entry.ppid == curpid {
			rss += memoryFor(procs, entry.pid)
		}
	}
	return rss
}

func (ps *processStorage) Collect(pid int) error {
	var err error

	ok, err := util.FileExists(ps.path)
	if err != nil {
		return err
	}

	if !ok {
		// we don't have the /proc filesystem, e.g. darwin or freebsd
		// use `ps` output instead.
		err = ps.capturePs(pid)
		if err != nil {
			return err
		}
	} else {
		err = ps.captureVM(pid)
		if err != nil {
			return err
		}

		err = ps.captureCPU(pid)
		if err != nil {
			return err
		}
	}

	for _, fn := range ps.dyncol {
		err = fn(pid, ps)
		if err != nil {
			return err
		}
	}

	for _, x := range ps.daemonSpecific {
		data, err := x.Capture()
		if err != nil {
			return err
		}
		for k, v := range data {
			ps.Save(x.Name(), k, v)
		}
	}
	return nil
}

/*
 * So many hacks in this.  OSX support can be seen as "bad" at best.
 */
func (ps *processStorage) capturePs(pid int) error {
	cmd := exec.Command("ps", "So", "rss,time,utime", "-p", strconv.Itoa(pid))
	sout, err := util.SafeRun(cmd)
	if err != nil {
		return err
	}

	lines, err := util.ReadLines(sout)
	if err != nil {
		return err
	}

	if len(lines) < 2 {
		return errors.New("Insufficient output from ps")
	}

	fields := strings.Fields(lines[1])
	val, err := strconv.ParseInt(fields[0], 10, 64)
	if err != nil {
		return err
	}

	ps.Save("memory", "rss", float64(1024*val))

	times := timeRegexp.FindStringSubmatch(fields[1])
	if times == nil {
		util.Debug("Unable to parse CPU time in " + lines[1])
		return nil
	}
	min, _ := strconv.ParseUint(times[1], 10, 32)
	sec, _ := strconv.ParseUint(times[2], 10, 32)
	cs, _ := strconv.ParseUint(times[3], 10, 32)

	ticks := min*60*100 + sec*100 + cs

	times = timeRegexp.FindStringSubmatch(fields[2])
	if times == nil {
		util.Debug("Unable to parse User time in " + lines[1])
		return nil
	}
	min, _ = strconv.ParseUint(times[1], 10, 32)
	sec, _ = strconv.ParseUint(times[2], 10, 32)
	cs, _ = strconv.ParseUint(times[3], 10, 32)

	uticks := min*60*100 + sec*100 + cs

	ps.Save("cpu", "user", float64(uticks))
	ps.Save("cpu", "system", float64(ticks-uticks))

	return nil
}

func (ps *processStorage) captureCPU(pid int) error {
	dir := ps.path + "/" + strconv.Itoa(int(pid))
	data, err := ioutil.ReadFile(dir + "/stat")
	if err != nil {
		return err
	}

	lines, err := util.ReadLines(data)
	if err != nil {
		return err
	}
	for _, line := range lines {
		if len(line) == 0 {
			continue
		}
		fields := strings.Fields(line)
		utime, err := strconv.ParseInt(fields[13], 10, 64)
		if err != nil {
			return err
		}
		stime, err := strconv.ParseInt(fields[14], 10, 64)
		if err != nil {
			return err
		}
		cutime, err := strconv.ParseInt(fields[15], 10, 64)
		if err != nil {
			return err
		}
		cstime, err := strconv.ParseInt(fields[16], 10, 64)
		if err != nil {
			return err
		}
		ps.Save("cpu", "user", float64(utime))
		ps.Save("cpu", "system", float64(stime))
		ps.Save("cpu", "total_user", float64(cutime))
		ps.Save("cpu", "total_system", float64(cstime))
	}

	return nil
}

func (ps *processStorage) captureVM(pid int) error {
	dir := ps.path + "/" + strconv.Itoa(int(pid))
	data, err := ioutil.ReadFile(dir + "/status")
	if err != nil {
		return err
	}

	lines, err := util.ReadLines(data)
	if err != nil {
		return err
	}
	for _, line := range lines {
		if len(line) == 0 {
			continue
		}
		if line[0] == 'V' {
			items := strings.Fields(line)
			switch items[0] {
			case "VmRSS:":
				val, err := strconv.ParseInt(items[1], 10, 64)
				if err != nil {
					return err
				}
				ps.Save("memory", "rss", float64(1024*val))
			}
		}

	}

	return nil
}
```

**Comment by mperham** [comment]
Good call, updated.

**Comment by gmartsenkov** [comment]
I was getting a similar error, but for nginx - basically, if the status endpoint does not exist inspeqtor fails to start with a vague error, had to dig in through the code to figure it out

**Comment by mperham** [comment]
Any idea why /status wouldn’t exist?

**Comment by allaire** [comment]
@mperham AFAIK `ngx_http_stub_status_module` is not built/setup by default.

http://nginx.org/en/docs/http/ngx_http_stub_status_module.html
https://www.datadoghq.com/blog/how-to-collect-nginx-metrics/

**Comment by mperham** [comment]
Oh, I was thinking of `/etc/<pid>/status`.  Nevermind.

**Comment by felixbuenemann** [comment]
I was also running into this with inspeqtor-1.0.1-1 on Ubuntu Xenial and Linux 4.4.0-128-generic.

Compiling Inspeqtor from master and replacing the binary on the server fixed the problem.

**Comment by kesha-antonov** [comment]
+1 have same issue

**Comment by kesha-antonov** [comment]
```
sudo service inspeqtor status
● inspeqtor.service - Inspeqtor
   Loaded: loaded (/lib/systemd/system/inspeqtor.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2018-06-19 20:31:37 UTC; 2s ago
  Process: 19189 ExecStart=/usr/bin/inspeqtor -c /etc/inspeqtor -s /var/run/inspeqtor.sock (code=exited, status=2)
  Process: 19186 ExecStartPre=/bin/rm -f /var/run/inspeqtor.sock (code=exited, status=0/SUCCESS)
 Main PID: 19189 (code=exited, status=2)

Jun 19 20:31:36 ip-172-31-20-112 inspeqtor[19189]:         /Users/mike/src/github.com/mperham/inspeqtor/types.go:148 +0x21d
Jun 19 20:31:36 ip-172-31-20-112 inspeqtor[19189]: created by github.com/mperham/inspeqtor.(*Inspeqtor).scan
Jun 19 20:31:36 ip-172-31-20-112 inspeqtor[19189]:         /Users/mike/src/github.com/mperham/inspeqtor/inspeqtor.go:295 +0x217
Jun 19 20:31:36 ip-172-31-20-112 systemd[1]: inspeqtor.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 19 20:31:36 ip-172-31-20-112 systemd[1]: inspeqtor.service: Unit entered failed state.
Jun 19 20:31:36 ip-172-31-20-112 systemd[1]: inspeqtor.service: Failed with result 'exit-code'.
Jun 19 20:31:37 ip-172-31-20-112 systemd[1]: inspeqtor.service: Service hold-off time over, scheduling restart.
Jun 19 20:31:37 ip-172-31-20-112 systemd[1]: Stopped Inspeqtor.
Jun 19 20:31:37 ip-172-31-20-112 systemd[1]: inspeqtor.service: Start request repeated too quickly.
Jun 19 20:31:37 ip-172-31-20-112 systemd[1]: Failed to start Inspeqtor.
```

**Comment by kesha-antonov** [comment]
How to fix it?

**Comment by kesha-antonov** [comment]
```
inspeqtor -v
Inspeqtor 1.0.1
```

**Comment by felixbuenemann** [comment]
> How to fix it?

* Install golang and make
* Clone the inspeqtor repo
* Run `make`
* Copy `inspeqtor` to `/usr/bin/inspeqtor`
* Restart inspeqtor service

Or wait for a new release…

**Comment by mperham** [comment]
Master is now 2.0.0-rc.  If someone wants to rebuild, smoke test it on their server and give me a thumbs up, I'll release 2.0.0.

**Comment by felixbuenemann** [comment]
I've installed the latest build from master on a server, I'll see how it goes.
